require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TrendsController do

  # This should return the minimal set of attributes required to create a valid
  # Trend. As you add validations to Trend, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TrendsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all trends as @trends" do
      trend = Trend.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trends).should eq([trend])
    end
  end

  describe "GET show" do
    it "assigns the requested trend as @trend" do
      trend = Trend.create! valid_attributes
      get :show, {:id => trend.to_param}, valid_session
      assigns(:trend).should eq(trend)
    end
  end

  describe "GET new" do
    it "assigns a new trend as @trend" do
      get :new, {}, valid_session
      assigns(:trend).should be_a_new(Trend)
    end
  end

  describe "GET edit" do
    it "assigns the requested trend as @trend" do
      trend = Trend.create! valid_attributes
      get :edit, {:id => trend.to_param}, valid_session
      assigns(:trend).should eq(trend)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Trend" do
        expect {
          post :create, {:trend => valid_attributes}, valid_session
        }.to change(Trend, :count).by(1)
      end

      it "assigns a newly created trend as @trend" do
        post :create, {:trend => valid_attributes}, valid_session
        assigns(:trend).should be_a(Trend)
        assigns(:trend).should be_persisted
      end

      it "redirects to the created trend" do
        post :create, {:trend => valid_attributes}, valid_session
        response.should redirect_to(Trend.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trend as @trend" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trend.any_instance.stub(:save).and_return(false)
        post :create, {:trend => { "name" => "invalid value" }}, valid_session
        assigns(:trend).should be_a_new(Trend)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trend.any_instance.stub(:save).and_return(false)
        post :create, {:trend => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trend" do
        trend = Trend.create! valid_attributes
        # Assuming there are no other trends in the database, this
        # specifies that the Trend created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Trend.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => trend.to_param, :trend => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested trend as @trend" do
        trend = Trend.create! valid_attributes
        put :update, {:id => trend.to_param, :trend => valid_attributes}, valid_session
        assigns(:trend).should eq(trend)
      end

      it "redirects to the trend" do
        trend = Trend.create! valid_attributes
        put :update, {:id => trend.to_param, :trend => valid_attributes}, valid_session
        response.should redirect_to(trend)
      end
    end

    describe "with invalid params" do
      it "assigns the trend as @trend" do
        trend = Trend.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trend.any_instance.stub(:save).and_return(false)
        put :update, {:id => trend.to_param, :trend => { "name" => "invalid value" }}, valid_session
        assigns(:trend).should eq(trend)
      end

      it "re-renders the 'edit' template" do
        trend = Trend.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trend.any_instance.stub(:save).and_return(false)
        put :update, {:id => trend.to_param, :trend => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trend" do
      trend = Trend.create! valid_attributes
      expect {
        delete :destroy, {:id => trend.to_param}, valid_session
      }.to change(Trend, :count).by(-1)
    end

    it "redirects to the trends list" do
      trend = Trend.create! valid_attributes
      delete :destroy, {:id => trend.to_param}, valid_session
      response.should redirect_to(trends_url)
    end
  end

end
